# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Mailgun/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Mailgun', class Mailgun extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
