# generated by Neptune Namespaces v3.x.x
# file: Art.Mailgun/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Mailgun'
.addModules
  Config: require './Config'