# generated by Neptune Namespaces v3.x.x
# file: Art.Mailgun/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Mailgun', class Mailgun extends Neptune.PackageNamespace
  @version: require('../../package.json').version
